target: mGPT.archs.mgpt_lm.MLM
params:
    model_type: t5
    # 通过设置huggingface的仓库名称，可以直接使用huggingface-cli下载
    model_path: google/flan-t5-base
    stage: ${TRAIN.STAGE}
    motion_codebook_size: ${model.params.codebook_size}
    ablation: ${ABLATION}
